
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tempo
  namespace: flux-system
spec:
  dependsOn:
  - name: kube-prometheus-stack
  interval: 10m0s
  path: ./releases/tempo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
