---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptrace
  namespace: flux-system
spec:
  targetNamespace: telemetry
  chart:
    spec:
      chart: uptrace
      sourceRef:
        kind: HelmRepository
        name: uptrace
      version: 0.2.16
  interval: 10m0s
  values:
    fullnameOverride: "uptrace"