
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: uptrace
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./releases/uptrace
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
