---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  targetNamespace: logging
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 10m0s
  values:
    loki:
      podLabels:
        generalized_service_type: observability
        generalized_service: loki
      image:
        tag: 2.6.1
      serviceMonitor:
        enabled: true
      env:
#        - name: JAEGER_AGENT_HOST
#          value: tracing-tempo.tracing.svc
        - name: JAEGER_AGENT_HOST
          value: otel-collector.monitoring.svc
        - name: JAEGER_SAMPLER_TYPE
          value: probabilistic
        - name: JAEGER_SAMPLER_PARAM
          value: "1"



